Reference: https://web.cse.iitk.ac.in/users/piyush/courses/ml-autumn18/771_A18_lec21_print.pdf

In [1]:
import numpy as np

In [4]:
#In this assignment I have to learn f(a, b, c) where a,b,c are boolean variables.
#Let's first try with f(abc) = abc i.e. boolean table will be as follows

#a b c | f
#0 0 0 | 0
#: : : | 0
#1 1 1 | 1


In [12]:
def sigmoid(x):
    return 1.0/(1+np.exp(-x))

In [35]:
def h_compute(W, xn):
    return sigmoid(np.dot(np.transpose(W), xn))

In [37]:
def output_compute(U, hn):
    return sigmoid(np.dot(np.transpose(U), hn))

In [71]:
x_train = np.array([[0, 0, 0], [1, 0, 0], [0, 1, 0], [0, 0, 1], [1, 1, 0], [0, 1, 1], [1, 0, 1],[1, 1, 1]])

Y_train = np.array([[0, 1, 1, 1, 0, 0, 0, 1], [0, 0, 0, 1, 0, 0, 0, 1],
                   [1, 0, 1, 0, 1, 0, 1, 0], [0, 0, 1, 0, 0, 0, 0, 0], [1, 1, 1, 1, 0, 0, 0, 0]])
y_pred = np.zeros((8, 1))

In [76]:
K = 4
N = 8
D = 3
EPOCHS = 10000
neta = 0.1

In [16]:
#Neural net architecture
#Input layer: 3 hidden nodes
#Hidden Layer: 1 hidden layer with 4 nodes
#Output Layer: 1 output node
#Activation function: Sigmoid

#At this step not considering bias term but you can include it in later stage
#W is the weight Matrix of first layer
#U is the weight vector of second layer

In [78]:
for y in Y_train:
    y_train = y.reshape(N, 1)
    W = np.random.randn(D, K)
    U = np.random.randn(K, 1)
    H = np.zeros((N, K))
    ERROR = np.zeros((N, 1))
    y_pred = np.zeros((8, 1))
    for i in range(EPOCHS):
        for j in range(N):
            H[j, :] = h_compute(W, x_train[j])
            y_pred[j] = output_compute(U, H[j, :])
            ERROR[j] = y_train[j] - y_pred[j]
        #U update weights
        for k in range(K):
            gradk = 0
            for n in range(N):
                gradk  += -ERROR[n]*H[n, k]*y_pred[n]*(1-y_pred[n])
            U[k] = U[k] - neta*gradk
        #W weight updates
        for d in range(D):
            for k in range(K):
                grad_w_dk = 0
                for n in range(N):
                    l1 = -ERROR[n]*U[k]*y_pred[n]*(1-y_pred[n])
                    l2 = x_train[n, d]*H[n, k]*(1-H[n ,k])
                    grad_w_dk += l1*l2   
                W[d, k] = W[d, k] - neta*grad_w_dk
    ###
    print("For boolean function of ")
    print (y_train)
    print ("The learnt values are")
    print (y_pred)

For boolean function of 
[[0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]]
The learnt values are
[[0.14238487]
 [0.93359429]
 [0.91335027]
 [0.91869531]
 [0.02269067]
 [0.02816727]
 [0.01213008]
 [0.99969081]]
For boolean function of 
[[0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]]
The learnt values are
[[0.0080583 ]
 [0.00320977]
 [0.01381601]
 [0.96607716]
 [0.00881657]
 [0.03534484]
 [0.02899045]
 [0.96207783]]
For boolean function of 
[[1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]]
The learnt values are
[[0.9872299 ]
 [0.27842075]
 [0.99958901]
 [0.28260905]
 [0.95473622]
 [0.02573127]
 [0.57190286]
 [0.01278858]]
For boolean function of 
[[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]]
The learnt values are
[[3.57652727e-02]
 [1.73179009e-04]
 [9.56755025e-01]
 [1.18008703e-04]
 [1.73497644e-02]
 [1.55019437e-02]
 [5.22451927e-05]
 [5.88501549e-04]]
For boolean function of 
[[1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]]
The learnt values are
[[0.99985968]
 [0.92587199]
 [0.92510432]
 [0.92209644]
 [0.06543696]
 [0.07

In [64]:
y_pred

array([[0.12692955],
       [0.9382959 ],
       [0.92218996],
       [0.92817161],
       [0.02178742],
       [0.02263153],
       [0.01032033],
       [0.99985865]])